version: '3.8'

services:
  # PostgreSQL Database (mit Healthcheck)
  postgres:
    image: postgres:15
    container_name: orgasuite-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: orgasuite
      POSTGRES_USER: orgasuite_user
      POSTGRES_PASSWORD: orgasuite_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orgasuite_user -d orgasuite"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - orgasuite-network

  # Backend API (wartet auf gesunde DB)
  backend:
    build: ./backend
    container_name: orgasuite-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgres://orgasuite_user:orgasuite_password@postgres:5432/orgasuite
      JWT_SECRET: orgasuite-super-secret-key-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - orgasuite-network

  # Frontend React App
  frontend:
    build: ./frontend
    container_name: orgasuite-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - orgasuite-network

  # pgAdmin (Database Management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: orgasuite-pgadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@orgasuite.de
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    networks:
      - orgasuite-network

volumes:
  postgres_data:

networks:
  orgasuite-network:
    driver: bridge